server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 512
    batchwait: 10s

scrape_configs:
  - job_name: story
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        filters:
          - name: name
            values: 
              - bootnode1-node
              - validator1-node
              - validator2-node
              - validator3-node
              - validator4-node
              
              - bootnode1-geth
              - validator1-geth
              - validator2-geth
              - validator3-geth
              - validator4-geth
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "service_name"
      - source_labels: ["__meta_docker_container_name"]
        regex: ".*-init"
        action: drop
